### PR TITLE
GridSizer.d.ts missing methods

### PR DESCRIPTION
**Pull request by hnegus1**
Have added missing methods to GridSizer.d.ts

Struggled to get this project running and had to install a new version of brower-sync (not very familiar with it), hopefully that's okay but let me know if I've done anything wrong and I can change it. Thanks.

### CODE REVIEW

**Comment by rexrainbow** [comment]
browser-sync-webpack-plugin and GridSizer.d.ts are two independent issues, would be better to split this PR to 2 separated PRs.
I would like to merge the GridSizer.d.ts updating, but for browser-sync-webpack-plugin... I am not so sure. 
Since browser-sync-v3-webpack-plugin is forked from browser-sync-webpack-plugin, I prefer keep older one.

**Comment by hnegus1** [comment]
No worries, I can remove the project setup changes, but I am getting a dependency error when I try to build it without the new plugin so the PR won't include the published files. Is that okay?

**Comment by rexrainbow** [comment]
Thanks, it is perfect, just submit GridSizer.d.ts.

( *dependency error* for browser-sync-webpack-plugin? I did not have that issue in my environment. )

**Comment by hnegus1** [comment]
Cool, I have reversed all changes but the ones to GridSizer.d.ts.

I'll make a separate issue about the dependency error, though it could just be something on my setup.

**Comment by rexrainbow** [comment]
Merged, thanks for this PR

**Pull request merged**
