### PR TITLE
use shallowcopy way instead of object.assign for LogicBoard

### PR DESCRIPTION
**Pull request by thecodejack**
Hey Rex, these Phaser tools are quite handy. Thanks for sharing these.

So I was trying to use same in one of my projects, was stuck due to a issue. I am using typescript in the project. Everything worked fine except using `Object.assign` to extend `class prototype`. Here is a [typescript playground](https://www.typescriptlang.org/play/index.html?ssl=13&ssc=25&pln=1&pc=1#code/MYGwhgzhAEAqCmEAu0De0BQ1vQB7QF4BGDAXwwwHkAjAK3mCQDpIIBLAcwDsAKBZJgAcATgHsk4gJ6D4AGjRYckgFzQATGQCUAbgqhWcREiLR4uJPC4ATGPxSpF2AF6FoAZjJ7RXCKJDwmEFEOHi54AHdDZCIeTU0gA) example. You can see property `y` is not getting set. 

I know that you are not supporting typescript as such but I think the PR shouldn't break javascript code as well. Also I feel this is safer approach than prototype way.

### CODE REVIEW

**Comment by rexrainbow** [comment]
Thanks for sharing this PR. However, *LogicBoardMethods* are all methods (function objects), no number or string member will be copied into LogicBoard class.

**Comment by thecodejack** [comment]
Yes. But even those aren't able to be available with child instance.

**Comment by rexrainbow** [comment]
The issue is not about using `Object.assign`, it is using `Object.assign` with `prototype`. Only can copy methods to prototype, not value members.
To attach value members into class, use `Object.assign` with `this` during constructor.

```javascript
class Test { 
    x =1
}

class Test1 extends Test {
    constructor() {
        super();
        Object.assign(this, {y:2});
        this.z = 3
    }
}

console.log(new Test1()) //{ "x": 1, "y": 2, "z": 3 } 
```

**Comment by thecodejack** [comment]
Agreed. That gonna work too. Can i update PR for same then?

**Comment by rexrainbow** [comment]
I still prefer coping methods on  prototype, not in constructor. Dose prototype extending break typescript?

**Comment by thecodejack** [comment]
yes. it's breaking in typescript.

Or can we try something like making all those object methods in to a class and extend eventemiter by same. So that board can just extend that class?

**Comment by thecodejack** [comment]
Ok. I can see wastage of time in TS support. Your call. 

Temporarily I will rebase the fork of your changes and use same. Thanks for being active in the discussion and sharing your thoughts.

**Comment by rexrainbow** [comment]
I can try Rich's solution in phaser3 -- *creating d.ts file from jsDoc*, instead of rewrite plugins by typescript. It might be more easier but still a time-consuming job.

**Pull request closed without merging**
