### PR TITLE
Some Batch File Tweaks

### PR DESCRIPTION
**Pull request by NoobTW**
As I mentioned in #1. There should be some tweaks.

Try to add `@echo off` on the top of every bat file to hide prompt, and use `npm run dev` instead of `webpack` to avoid installing webpack globally.

### CODE REVIEW

**Comment by NoobTW** [comment]
This isn't going to merge? 🤔

**Comment by rexrainbow** [comment]
This PR had been merged already.

**Comment by rexrainbow** [comment]
Approved

**Comment by rexrainbow** [comment]
@NoobTW 
Okey, now this PR had been merged correctly. My mistake.

**Pull request merged**
